# Subpart 5: Weekly changes in number of hotspots per state

In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

Reading the csv file and filtering the cases

In [12]:
cols=['detected_district','status_change_date','current_status','detected_state']
ind_cases=pd.read_csv('IndividualDetails.csv', parse_dates =['status_change_date'], dayfirst=True,usecols=cols)
ind_cases =ind_cases.dropna()
ind_cases =ind_cases[ind_cases['current_status']=="Hospitalized"]

Determining the week 1 hotspots

In [20]:
week1 = '2020-03-27'
df =ind_cases[ind_cases.status_change_date <=week1]
df['Active']=df.groupby('detected_district')['detected_district'].transform('count')
df=df[['detected_district','Active','detected_state']]
df=df.drop_duplicates()
df['Hotspots1']=df.groupby('detected_state')['detected_state'].transform('count')
df=df[['detected_state','Hotspots1']]
df=df.drop_duplicates()
df

D:\conda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

        detected_state  Hotspots1
18             Haryana          7
21       Uttar Pradesh         11
28               Delhi          7
31              Ladakh          2
40   Jammu and Kashmir          4
45              Punjab          6
49              Kerala         11
59         Maharashtra         15
100          Rajasthan          9
101          Telangana          5
111        Uttarakhand          2
124             Odisha          1
139         Puducherry          1
153         Tamil Nadu          9
171         Chandigarh          1
175     Andhra Pradesh          6
183            Gujarat          6
198        West Bengal          2
244   Himachal Pradesh          1
246     Madhya Pradesh          6
284          Karnataka          4
348              Bihar          4
586            Mizoram          1
654                Goa          1

Selecting and displaying the states with the maximum hotspots in the first week

In [21]:
week1_hotspots=df.sort_values('Hotspots1', ascending=False).reset_index(drop=True)
week1_hotspots.head()

  detected_state  Hotspots1
0    Maharashtra         15
1  Uttar Pradesh         11
2         Kerala         11
3      Rajasthan          9
4     Tamil Nadu          9

Determining the week 2 hotspots

In [23]:
week2='2020-04-03'
df =ind_cases[ind_cases.status_change_date <=week2]
df['Active']=df.groupby('detected_district')['detected_district'].transform('count')
df=df[['detected_district','Active','detected_state']]
df=df.drop_duplicates()
df['Hotspots2']=df.groupby('detected_state')['detected_state'].transform('count')
df=df[['detected_state','Hotspots2']]
df=df.drop_duplicates()
df

D:\conda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

         detected_state  Hotspots2
18              Haryana         13
21        Uttar Pradesh         23
28                Delhi          7
31               Ladakh          2
40    Jammu and Kashmir          7
45               Punjab          7
49               Kerala         13
59          Maharashtra         21
100           Rajasthan         18
101           Telangana         13
111         Uttarakhand          3
124              Odisha          5
139          Puducherry          2
153          Tamil Nadu         27
171          Chandigarh          1
175      Andhra Pradesh         11
183             Gujarat         11
198         West Bengal          6
244    Himachal Pradesh          2
246      Madhya Pradesh          8
284           Karnataka         12
348               Bihar          9
586             Mizoram          1
654                 Goa          1
1325       Chhattisgarh          1
1441          Jharkhand          2
1452              Assam          8
2059            Manipur          1
2093  Arunachal Pradesh          1

Selecting and displaying the states with the maximum hotspots in the second week

In [24]:
week2_hotspots=df.sort_values('Hotspots2', ascending=False).reset_index(drop=True)
week2_hotspots.head()

  detected_state  Hotspots2
0     Tamil Nadu         27
1  Uttar Pradesh         23
2    Maharashtra         21
3      Rajasthan         18
4        Haryana         13

Determining the week 3 hotspots

In [27]:
week3='2020-04-17'
df =ind_cases[ind_cases.status_change_date <=week3]
df=df.sort_values(by='status_change_date',ascending=False)
df['Active']=df.groupby('detected_district')['detected_district'].transform('count')
df=df.drop_duplicates()
df['Hotspots3']=df.groupby('detected_state')['detected_state'].transform('count')
df=df[['detected_state','Hotspots3']]
df=df.drop_duplicates()

Selecting and displaying the states with the maximum hotspots in the third week

In [28]:
week3_hotspots=df.sort_values('Hotspots3', ascending=False).reset_index(drop=True)
week3_hotspots.head()

  detected_state  Hotspots3
0     Tamil Nadu        264
1    Maharashtra        229
2  Uttar Pradesh        226
3      Rajasthan        181
4        Gujarat        149

Weekwise hotspots for all the states

In [29]:
week_wise=week1_hotspots.merge(week2_hotspots)
week_wise=week_wise.merge(week3_hotspots)
week_wise

       detected_state  Hotspots1  Hotspots2  Hotspots3
0         Maharashtra         15         21        229
1       Uttar Pradesh         11         23        226
2              Kerala         11         13        122
3           Rajasthan          9         18        181
4          Tamil Nadu          9         27        264
5             Haryana          7         13         73
6               Delhi          7          7         15
7             Gujarat          6         11        149
8      Andhra Pradesh          6         11        119
9              Punjab          6          7         89
10     Madhya Pradesh          6          8        132
11          Telangana          5         13        110
12              Bihar          4          9         40
13  Jammu and Kashmir          4          7         80
14          Karnataka          4         12        104
15        Uttarakhand          2          3         19
16             Ladakh          2          2         12
17        West Bengal          2          6         13
18            Mizoram          1          1          1
19         Puducherry          1          2          4
20   Himachal Pradesh          1          2         12
21         Chandigarh          1          1         11
22             Odisha          1          5         24
23                Goa          1          1          2

Calculating and displaying the states which have the maximum increase in hotspots between the first and second week

In [30]:
#max increase in week 1-2
week_wise_dif1=week_wise[['detected_state']]
week_wise_dif1['Increase']=week_wise['Hotspots2']-week_wise['Hotspots1']
week_wise_dif1=week_wise_dif1.sort_values('Increase',ascending=False).reset_index(drop=True)
week_wise_dif1=week_wise_dif1.rename(columns={'detected_state': 'States with highest increase from W1 to W2'})
week_wise_dif1.head()

D:\conda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

  States with highest increase from W1 to W2  Increase
0                                 Tamil Nadu        18
1                              Uttar Pradesh        12
2                                  Rajasthan         9
3                                  Karnataka         8
4                                  Telangana         8

Calculating and displaying the states which have the maximum increase in hotspots between the second and third week

In [31]:
week_wise_dif2=week_wise[['detected_state']]
week_wise_dif2['Increase']=week_wise['Hotspots3']-week_wise['Hotspots2']
week_wise_dif2=week_wise_dif2.sort_values('Increase',ascending=False).reset_index(drop=True)
week_wise_dif2=week_wise_dif2.rename(columns={'detected_state': 'States with highest increase from W2 to W3'})
week_wise_dif2.head()

D:\conda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

  States with highest increase from W2 to W3  Increase
0                                 Tamil Nadu       237
1                                Maharashtra       208
2                              Uttar Pradesh       203
3                                  Rajasthan       163
4                                    Gujarat       138

Calculating and displaying the states which have the maximum decrease in hotspots between the first and second week

In [32]:
week_wise_dec1=week_wise[['detected_state']]
week_wise_dec1['Decrease']=week_wise['Hotspots1']-week_wise['Hotspots2']
week_wise_dec1=week_wise_dec1.sort_values('Decrease',ascending=False).reset_index(drop=True)
week_wise_dec1=week_wise_dec1.rename(columns={'detected_state': 'States with highest decrease from W1 to W2'})
if week_wise_dec1['Decrease'][0] ==0:
    print("There is no state that shows a decrease of hotspots between Week 1 and Week 2")
else:
    week1_dec=week_wise_dec1.loc[week_wise_dec1['Decrease'] > 0]
    week1_dec.head()

There is no state that shows a decrease of hotspots between Week 1 and Week 2

D:\conda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

Calculating and displaying the states which have the maximum decrease in hotspots between the second and third week

In [33]:
week_wise_dec2=week_wise[['detected_state']]
week_wise_dec2['Decrease']=week_wise['Hotspots1']-week_wise['Hotspots2']
week_wise_dec2=week_wise_dec2.sort_values('Decrease',ascending=False).reset_index(drop=True)
week_wise_dec2=week_wise_dec2.rename(columns={'detected_state': 'States with highest decrease from W1 to W2'})
if week_wise_dec2['Decrease'][0] ==0:
    print("There is no state that shows a decrease of hotspots between Week 2 and Week 3")
else:
    week2_dec=week_wise_dec2.loc[week_wise_dec2['Decrease'] > 0]
    week2_dec.head()

There is no state that shows a decrease of hotspots between Week 2 and Week 3

D:\conda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy